### ISSUE TITLE
Playback marker skips forward even after start position is set on play occasionally

### ISSUE THREAD

**Issue by ahemtoday** [chrislo27/RhythmHeavenRemixEditor2#53]
This only happens when the playback marker is at a nonzero position, and it can affect cues up to 6 beats away.

**Comment by chrislo27** [comment]
Is this absolute or only when the cues are behind it? Also, next time use the issue template or at least include the version.

**Comment by chrislo27** [comment]
Can you provide a step-by-step way to reproduce this bug?

**Comment by Pengu12345** [comment]
Yes, I got this bug many times when I make custom remixes. But It's kinda random so it's hardly perfectly reproducable step by step.

**Comment by chrislo27** [comment]
This is caused by the music's position not internally updating fast enough and the tracker is interpolating between the actual playback position and the music's old position. I'll try to fix this by resetting the music position when stopping + when you move the tracker but there's a high chance it may still happen under certain circumstances.
